version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
before_package:
- cmd: dotnet pack /p:Version=%APPVEYOR_BUILD_VERSION%
test_script:
- ps: >-
    #run tests

    dotnet test "--logger:trx;LogFileName=results.trx"


    # upload results to AppVeyor

    $files = Get-ChildItem -Path ".\" -Recurse -Include *.trx


    $files | Foreach-Object {


    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", $_.FullName)


    }
artifacts:
- path: '**\*.nupkg'
  name: NugetPackages
- path: '**\*.dll'
  name: Assemblies
deploy: off